# Other Cool Applications with the FFT

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eig_banded
from scipy.special import erf
from scipy.fftpack import ifft, fft, fftshift, ifftshift
%matplotlib inline

### Clenshaw-Curtis Quadrature

In [2]:
n1 = 33
n = n1 - 1
C = np.zeros((n1,2))
k = 2*(1+np.arange(np.floor(n/2)))
# Compute weights --> integral of Tn(x)
C[::2,0] = 2/np.hstack((1, 1-k*k))
C[1,1] = -n
V = np.vstack((C,np.flipud(C[1:n,:])))
# Real part of inverse FFT ~ Cosine transform
F = np.real(ifft(V, n=None, axis=0))
x = F[:n1,1]
w = np.hstack((F[0,0],2*F[1:n,0],F[n,0]))

y = np.exp(-np.sin(x))
I = np.dot(w,y)
print("Integral: {}".format(I))

Integral: 2.2831945209105777


### Fast Polynomial Multiplication

In [3]:
a = np.array([3,-1,2,7])
b = np.array([-5,4,9,-3])
np.convolve(a,b)

array([-15,  17,  13, -45,  49,  57, -21])

In [4]:
apad = np.append(a,np.zeros(len(a)-1))
bpad = np.append(b,np.zeros(len(b)-1))
np.real(ifft((fft(apad)*fft(bpad))))

array([-15.,  17.,  13., -45.,  49.,  57., -21.])

In [5]:
%%timeit -n 100
a = np.random.rand(5000)
apad = np.append(a,np.zeros(len(a)))
b = np.random.rand(5000)
bpad = np.append(b,np.zeros(len(b)))
np.real(ifft((fft(apad)*fft(bpad))))

659 µs ± 123 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%%timeit -n 100
a = np.random.rand(5000)
b = np.random.rand(5000)
np.convolve(a,b)

9.43 ms ± 1 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
A = np.array([[2,-2,1],[1,-1,2],[1,1,1]])
b = np.array([2,4,4])
np.linalg.solve(A,b)

array([1., 1., 2.])